### ISSUE TITLE
CIGAR operation longer than 268Mb causes OverflowError

### ISSUE THREAD

**Issue by eldariont** [pysam-developers/pysam#1004]
Hi,

first of all, thanks for providing this super helpful library! I'm using it in my software to process BAM files from whole genome alignments where the query sequences can potentially be very long.

Recently, a user of my tool reported an `OverflowError` raised by pysam (see https://github.com/eldariont/svim-asm/issues/5). It was caused by a CIGAR operation that was longer than 2^28=268.435.456.

I could reproduce the Exception on pysam 0.16.0.1 with the following minimal example:
```
a = pysam.AlignedSegment()
a.query_name = 'read1'
a.query_sequence = ''
a.flag = 2048
a.reference_id = 1
a.reference_start = 100
a.mapping_quality = 60
a.cigarstring = "268435455S10000M100S" # no error raised
a.cigarstring = "268435456S10000M100S" # OverflowError
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "pysam/libcalignedsegment.pyx", line 1306, in pysam.libcalignedsegment.AlignedSegment.cigarstring.__set__
#   File "pysam/libcalignedsegment.pyx", line 2224, in pysam.libcalignedsegment.AlignedSegment.cigartuples.__set__
# OverflowError: value too large to convert to uint32_t
```

I'm not sure why the maximal value uint32_t should be 2^28 but apparently that's the case on my system.

I think it would be good to support CIGAR operations longer than that because it is not uncommon to see chromosomes longer than this size. Do you know where the cause of this problem lies? Is it in htslib or even the BAM specification? I read about the limit on the number of CIGAR operations but never about a limit on the length of each operation. Are you aware of such a limit in the specification?

Cheers
David

**Comment by jmarshall** [comment]
Each CIGAR operation is stored in a `uint32_t` in BAM, with 4 bits used to represent the operator character — hence the limitation on the operation length you have seen. This is a limitation of the BAM format; see the table in §4.2 of the [SAM specification](http://samtools.github.io/hts-specs/SAMv1.pdf).

This is effectively a limitation on practical read length representable in this format. It is not a limitation on chromosome size.

**Comment by eldariont** [comment]
Thanks a lot for the explanation. That makes sense. For a whole genome assembly, a limit on the read length is in practice a limit on the chromosome size. But there's probably not much that can be done about it except using another format.

**Comment by jmarshall** [comment]
It's almost like directly representing an assembly with one read = one scaffold was not a design goal of the BAM format. :smile:

It may confuse some tools (but your immensely long reads will already confuse them anyway), but it is only a recommendation that adjacent CIGAR operators be different. So you could represent e.g. a 2<sup>29</sup> bp read with the CIGAR string `268435455M268435455M2M`.

(Pysam and htslib's internal CIGAR representation uses `uint32_t`s, so regardless of whether other formats like CRAM share this limitation, the implementation will raise `OverflowError` in the same way.)

**Comment by eldariont** [comment]
> It's almost like directly representing an assembly with one read = one scaffold was not a design goal of the BAM format. 😄

Yeah, I guess you could be right about that 😄 Nevertheless, using BAM/htslib/pysam works very well for genome alignments of human or smaller genomes. For larger genomes (like the one analyzed by the user reporting this issue) we probably need to use other formats like [PAF](https://github.com/lh3/miniasm/blob/master/PAF.md) for which we can of course not use pysam anymore.

Thanks again for clearing this up for me!
Cheers
David

**Comment by jmarshall** [comment]
Or carry on using BAM but be a bit more careful about constructing your CIGAR strings (as described above) to avoid this limitation.

**Comment by jkbonfield** [comment]
At some point we probably ought to consider a `sam_read2` function in htslib with `bam2_t` struct that has fewer limitations, so other formats (eg CRAM) can be processed without suffering the limits of the BAM format.  Having the in-memory format as BAM has been great for speed, but things have moved on somewhat.  It's a major change though, so it's debatable if it's just easier done as a major version bump with ABI/API breakage instead of doubling up function names/structs.  Down the road somewhere...

Don't underestimate the power of bgzipped SAM either!  It's not particularly small compared to CRAM, but it's on marginally smaller than BAM and has many fewer format limitations.  It's not even that slow either.  Reading 10 million BAM records and writing to SAM.gz, BAM and CRAM (4 threads) took 22s, 20s and 11s respectively.  Reading them back took 3.0s, 3.0s and 3.4s (4 threads again).

Does pysam support indexed SAM.gz?

PS.  If only VCF performance was as close to BCF as SAM is to BAM. :-(
