### ISSUE TITLE
AlignedSegment.__str__  uses query_alignment_length instead of template_length

### ISSUE THREAD

**Issue by goranvinterhalter** [pysam-developers/pysam#1040]
I would expect `__str__` to try and follow the output style of `to_string`.
But, before the sequence, instead of template_length,  query_alignment_length is used.
In `to_dict` it seams like template_length is used and outputted under the dict key `length` (not sure if this is intended?).

**Comment by jmarshall** [comment]
You are correct, `__str__` should be using `self.template_length`.

It also differs from `to_string` and real SAM format in that the POS and MPOS fields are displayed 0-based rather than 1-based. I am in two minds whether it is better to add that to the `__str__` documentation (alongside the discussion of the raw `tid` being displayed) or to change them to be displayed 1-based as expected in SAM format.

**Comment by goranvinterhalter** [comment]
Ahh the pain... @jmarshall whatever you choose, it will make someone unhappy.
