### ISSUE TITLE
documentation: is region string1-based on 0-based?

### ISSUE THREAD

**Issue by aretchless** [pysam-developers/pysam#1068]
I am confused about how positions in the 'samtools compatible region strings' are indexed.

The pysam [documentation ](https://pysam.readthedocs.io/en/latest/glossary.html#term-region)says:

> region
> A genomic region, stated relative to a reference sequence. A region consists of reference name (‘chr1’), start (10000), and end (20000). Start and end can be omitted for regions spanning a whole chromosome. If end is missing, the region will span from start to the end of the chromosome. **Within pysam, coordinates are 0-based, half-open intervals**, i.e., the position 10,000 is part of the interval, but 20,000 is not. An exception are samtools compatible region strings such as ‘chr1:10000-20000’, which are closed, i.e., both positions 10,000 and 20,000 are part of the interval.

I interpret this to mean that the region string is also 0-based since it does not specify otherwise and the same coordinates are used for both examples (start/end and region string). However, according to the s[amtools documentation](http://www.htslib.org/doc/samtools-view.html), their region strings are 1-based. 

>Regions can be specified as: RNAME[:STARTPOS[-ENDPOS]] and all position coordinates are 1-based.

Could someone clarify whether the pysam region strings are 0-based or 1-based?

Thanks.

**Comment by aretchless** [comment]
Update: I did some testing and it looks like the region string is 1-based.

**Comment by jmarshall** [comment]
The general rule is that where a region is represented as three parts `rname`/`start`/`end` where `start` and `end` are Python integers, then `start` and `end` are 0-based and represent a half-open interval (because this is an arithmetic-oriented representation). Where a region is represented as a single string, this is a human-oriented representation and the start/end within the string are 1-based and represent a closed interval.

Are there any other particular parts of the documentation (besides the glossary entry you pointed to) that you consider present regions confusingly?

**Comment by aretchless** [comment]
Thanks @jmarshall -- the glossary entry is the only definition I was using.  The documentation seems to consistently point to that glossary.
