### ISSUE TITLE
Compatibility with newer setuptools

### ISSUE THREAD

**Issue by frenzymadness** [pysam-developers/pysam#1113]
This line in the config of documentation:
https://github.com/pysam-developers/pysam/blob/5eac009c5e85d280e8bbcb69ed0fa081e2271d78/doc/conf.py#L20
is not compatible with the latest setuptools because the path is different - for example `lib.linux-x86_64-cpython-311`.

**Comment by jmarshall** [comment]
Brillant. I see this arrived with pypa/setuptools@1c23f5e1e4b18b50081cbabb2dea22bf345f5894, which appeared in 62.1.0 in April but was not considered interesting enough to point out as a change in the [Changelog](https://setuptools.pypa.io/en/latest/history.html#v62-1-0).

Thanks for reporting this. `distutils_dir_name()` in _setup.py_ will also be affected. OTOH `class extra_build` is not affected, because it queries the build path from `build_ext_obj`. Hopefully there's a simple way to query this path directly and these other two routines can be changed to do something similar.

**Comment by frenzymadness** [comment]
I'm also very surprised that the change we have full hands of work with was not considered important enough for an entry in the changelog.

**Comment by jmarshall** [comment]
The instance in _setup.py_ can be fixed using `self.build_lib` or `self.build_platlib` if the bulk of _setup.py_ can be reorganised to be within an appropriately overridden `build` or `build_ext` class (which is an ongoing project of mine).

The instance in _doc/conf.py_ does not necessarily have the build infrastructure available, so may need to find the build_lib directory via `glob` instead.

**Comment by jmarshall** [comment]
Since 4792ecf8f7570a636c944cc0985a89221ce891d0 there are no hand-computed build directories; instead they are always queried from setuptools where needed.
