### ISSUE TITLE
bioconda recipe: support python 3.10

### ISSUE THREAD

**Issue by nick-youngblut** [pysam-developers/pysam#1114]
`mamba create -n pysam_env python=3.10 bioconda::pysam` results in:

```
Looking for: ['python=3.10', 'bioconda::pysam']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
r/linux-64                                                  Using cache
r/noarch                                                    Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/main/noarch                                              No change
pytorch/noarch                                                No change
pytorch/linux-64                                              No change
qiime2/linux-64                                               No change
leylabmpi/noarch                                              No change
pkgs/r/noarch                                        1.3MB @   3.7MB/s  0.3s
pkgs/r/linux-64                                      1.4MB @   3.8MB/s  0.4s
qiime2/noarch                                                 No change
leylabmpi/linux-64                                            No change
pkgs/main/linux-64                                   4.5MB @   5.2MB/s  0.9s
Encountered problems while solving:
  - package pysam-0.7.7-0 requires python <3.0.0, but none of the providers can be installed
```

Users currently have to go with `mamba create -n pysam_env python=3.9 bioconda::pysam`

**Comment by nataquinones** [comment]
Getting similar issue!
```
Pinned packages:
  - python 3.10.*


Could not solve for environment specs
Encountered problems while solving:
  - package pysam-0.19.1-py310hff46b53_1 requires libdeflate >=1.13,<1.14.0a0, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

**Comment by jkbonfield** [comment]
Is there a *valid* reason to cap the highest version number?  The current upstream libdeflate is 1.18.  Wanting between 1.13 and 1.14 seems broken.  I suspect it'll work fine with newer code, as htslib has been using libdeflate for a long while and we've yet to see a conflict.

This isn't the sort of thing people should have to use environments to work around.  It's the sort of thing conda package maintainers should avoid specifying.

**Comment by jmarshall** [comment]
@nick-youngblut: The bioconda package has been built for Python 3.10 since pysam 0.19.1 in August 2022. That timing was a function of bioconda's build infrastructure, and not under the control of the pysam project.

@nataquinones: The usual reason for an error like that is that you haven't [set up the channels required by bioconda](https://bioconda.github.io/#usage), in particular that you are missing conda-forge. Note that pysam-0.19.1 is outdated at this point; you may wish to select the current version with `pysam=0.21.0`. If the problem persists after updating your channels, please open a new issue (ideally at bioconda/bioconda-recipes) providing some more of the output produced when things go wrong.

@jkbonfield: As I've explained before, the [conda build system pins shared library dependency versions because conda packages do not track soversion dependencies](https://twitter.com/jomarnz/status/1298187919786741762). Conda package maintainers generally do not specify such version ranges (pysam certainly does not), so there's not much point complaining here. If you do want to help improve this (e.g., apparently these days it is more practical to retropatch packages like these to have wider libdeflate version ranges as time moves on and the future arrives and we know that now-extant libdeflate versions have not bumped their soversion), you should talk to bioconda-core or conda-forge.

(Libdeflate 1.13 may not have been current even back when pysam 0.19.1 was released and the package built; this is bioconda/bioconda-utils#871.)

I'll close this issue, as the OP's 3.10 issue has since been addressed.
