### ISSUE TITLE
count() doubts

### ISSUE THREAD

**Issue by sbtmnl** [pysam-developers/pysam#1133]
Dear Pysam users,
i need of help! =)
i m using the code 

samfile = pysam.AlignmentFile("1_S1.bam", "rb")
samfile.count('chr6', until_eof=False)
samfile.count('chr6', until_eof=True)

to know the number of mapped and unmapped read of entire chromosome 6.
the numbers that i m obtaining are  4330338 and 4330338 respectively.
the first doubt is how is it possible to obtain the same quantity?

when i run the code

samfile.get_index_statistics()

I obtain on 6th chromosome :
IndexStats(contig='chr6', mapped=4322872, unmapped=7466, total=4330338)

why the total reads are equal to the results of the others command?
in theory samfile.count results should be  4322872 and 7466 respectively?
how is it possible?could someone to help me to understand the question?

thanks! =)

Manuela

**Comment by jmarshall** [comment]
Because you are specifying `'chr6'`, both count calls are using the index to count the reads whose `RNAME` fields place them on chr6, so they produce the same results. `until_eof` only has an effect if you do not specify a particular region to count.

The default for `count()`'s `read_callback` parameter is `nofilter`, so both `count()` calls count all the reads placed on chr6 (i.e., with RNAME = chr6) whether they are mapped or unmapped. Hence they both return 4330338, the total recorded in the index statistics, as expected.

`samfile.count('chr6', read_callback='all')` would probably give you 4322872. You would need to construct a `read_callback` function to return True only for unmapped reads to get a count of 7466.

Further details would be a question that is better asked on a forum such as [Biostars](https://www.biostars.org/) or [bioinformatics.SE](https://bioinformatics.stackexchange.com/), where there are more pysam users available to help you.

**Comment by sbtmnl** [comment]
thank you! now it is clearer!
=)

the next time i will write on Biostars or bioinformatics.SE!

=)
