### ISSUE TITLE
find_introns does not handle reads without CIGAR strings

### ISSUE THREAD

**Issue by GSS-Investigator** [pysam-developers/pysam#1148]
I've been trying to utilize pysam's find_introns to find introns per contig and strand, however, attempting to use .is_forward results in the error:

> Traceback (most recent call last):
>   File "~/scratch_10.py", line 26, in <module>
>     introns = bamfile.find_introns([read for read in fetched_seq if read.is_forward])
>   File "pysam/libcalignmentfile.pyx", line 1653, in pysam.libcalignmentfile.AlignmentFile.find_introns
> TypeError: 'NoneType' object is not iterable

This error doesn't occur when using .is_reverse with the same function, and it produces the expected collection output.

I asked a post doc in the lab if he could run the same code on his genome/bam file and he received the same error, so it doesn't seem to be specific to this set of RNA data. Similarly, when running the commands outside of any sort of loop, the same error occurs (and doesn't occur for .is_reverse).

Code:
```py
import pysam

in_bam="Example_bam.bam"
all_contigs = ['Seq_38']

bamfile=pysam.AlignmentFile(in_bam, mode="rb")

bam_list=bamfile.fetch()

for seq in all_contigs:
    fetched_seq=bamfile.fetch(contig=seq)
    for strand in ['+', '-']:
        if strand == "+":
            introns = bamfile.find_introns([read for read in fetched_seq if read.is_forward])
            [print(x, introns[x]) for x in introns]

```

I've uploaded the bamfile in question
[Example_bam.bam.zip](https://github.com/pysam-developers/pysam/files/9982665/Example_bam.bam.zip)

Thanks,

**Comment by jmarshall** [comment]
What version of pysam are you using?

**Comment by GSS-Investigator** [comment]
> What version of pysam are you using?

I wanted to update that I tried with pysam 0.20.0 and I'm still encountering the same problem.

**Comment by GSS-Investigator** [comment]
After some work by myself and others in the lab, I believe we've identified in part the issue that's causing this error.

Upon closer investigation, we were able to get the code to work with a line like:
`for seq in all_contigs:

    fetched_seq=bamfile.fetch(contig=seq)

    for strand in ['+', '-']:

        if strand == "+":

            introns = bamfile.find_introns([read for read in fetched_seq if (read.is_forward and read.cigarstring is not None])`

While this worked it was a bit odd since the cigarstring doesn't seem to have anything to do with orientation. However, by getting pysam to return reads that were both .is_forward and .cigarstring is None, I realized that the reads in question lacked the cigarstring all together due to them being unmapped. Notably, these reads also lacked most of the tags that occupy the optional alignment section of a read in the samfile. Accounting for these unmapped reads produces introns as expected:
`introns= bamfile.find_introns([read for read in fetched_seq if (read.is_forward and read.is_mapped)]`

(This also appears to require a higher version of python than what I was using originally: python 3.7 results in an error, but this works with python 3.10)

In general, I think what's happening here is that .is_forward is implemented in terms of .is_reverse, rather than being explicitly defined. Because of this, .is_forward picks up unmapped reads and this causes a problem for the fetch_introns function. While the above ("and read.is_mapped") it maybe worthwhile explicitly defining .is_forward in pysam, or introducing some sort of filter step to the fetch_intron function that removes unmapped reads.

**Comment by jmarshall** [comment]
Both `is_forward` and `is_reverse` are defined directly, in terms of the underlying SAM record's FLAG bit 0x10.

The problem is nothing to do with `is_forward` itself.

As you have correctly surmised, the problem is that `find_introns()` has never been able to deal with reads that do not have CIGAR strings. The way to work around this is with `[read for read in fetched_seq if read.is_forward and read.is_mapped]` or `[read for read in fetched_seq if read.is_reverse and read.is_mapped]` as appropriate.

Typically reads that have the reverse bit set have it because they have been mapped, whereas for actually unmapped reads `is_forward` is usually true and `is_reverse` is usually false, because the reverse bit is usually corresponding unset. So it would be more common to encounter this problem when looking at forward reads than reverse reads, as you have found. (But it is not impossible to encounter this problem when looking at reverse reads; e.g. some versions of bwa unhelpfully sometimes emit unmapped "reversed" reads.)

We will fix `find_introns()` so that it skips unmapped reads and any other reads that do not have CIGAR strings. They don't have any N operations so don't contribute to the count, so skipping them does not change the result.
