### ISSUE TITLE
[W::bcf_update_info] INFO/END=0 is smaller than POS at chr1:1

### ISSUE THREAD

**Issue by arpanda** [pysam-developers/pysam#1175]
The below code([colab link](https://colab.research.google.com/drive/14n79JMVsBwW71metf12RB_arTWjA2sUx?usp=sharing)) is used to create a VCF file.

```python
import pysam


vcfh = pysam.VariantHeader()

vcfh.add_meta('FILTER', items=[('ID',"RF"), ('Description','Variant failed filter due to low RF')])
vcfh.add_meta('ALT', items=[('ID', "DEL"), ('Description', 'Deletion')])
vcf = pysam.VariantFile("example.vcf", "w", header=vcfh)

call=['chr1', 180001, 220000, 40000]

vcf.header.contigs.add(str(call[0]))
r = vcf.new_record(contig=str(call[0]), start=180001, stop=220000, alleles=('.', "<DUP>"), id="Test_1", filter="PASS")

print(r)

vcf.write(r)
vcf.close()
```

But getting an message saying
```
[W::bcf_update_info] INFO/END=0 is smaller than POS at chr1:1
chr1	180002	Test_1	.	<DUP>	.	PASS	END=220000
```

Not sure what promoting the message `[W::bcf_update_info] ..`. Any suggestion to fix?

**Comment by jmarshall** [comment]
Thanks for the report. This is a warning that was added in HTSlib 1.11 or so to help detect invalid INFO/END values. In this case, the ‘invalid’ values are 0 and 1 because the coordinates have not been set up by `new_record` yet! This is easily fixed within `new_record` and an upcoming pysam release will not print this message.
