### ISSUE TITLE
PySAM installation on macbook Pro M2

### ISSUE THREAD

**Issue by Taslimi** [pysam-developers/pysam#1192]
Hello, 
I am working with a macbook Pro M2, I have installed pyhton3. 11, and I have installed PySAM using "pip install PySAM" in the terminal. However, I cannot use and import PySAM in my python environment. I have tried it with jupyter and visual studio code. Please help me figure it out!
Thanks

**Comment by safay** [comment]
There may be an issue with the binary dependencies for pysam.

Have you tried using conda, as recommended in the docs? https://pysam.readthedocs.io/en/latest/installation.html

**Comment by jmarshall** [comment]
There aren't really any details here of what went wrong. Since this issue was opened, pysam 0.22.0 has been released and includes pre-built wheels for Apple silicon macOS. So since early October, `pip install pysam` on Python ≥3.9 will install relatively painlessly via a binary wheel.

So this problem should have since been resolved. Please comment or re-open if problems persist.
