### ISSUE TITLE
No option to flush VariantFile.write() (or at least undocumented)

### ISSUE THREAD

**Issue by blex-max** [pysam-developers/pysam#1299]
Output is not written until the program completes. Is this something that could be added? Many thanks for your work.

**Comment by jmarshall** [comment]
Much as with ordinary Python I/O streams, you should call `myvariantfile.close()` when you have finished writing to it to ensure the output is flushed and the file closed in a timely fashion.

There are a couple of improvements that pysam could make in this area:

* There is an underlying HTSlib `hts_flush()` function that `VariantFile`, `AlignmentFile`, etc could expose as a `flush()` method. However I suspect most code would not really benefit from being able to do this.

* `VariantFile`, `AlignmentFile`, etc could implement the [context manager methods](https://docs.python.org/3/reference/datamodel.html#with-statement-context-managers) so that the following would ensure the file is closed at the end of the `with` statement:

```python
with pysam.VariantFile('foo.vcf', 'w') as f:
    f.write(record)
    …etc…

**Comment by blex-max** [comment]
In my case I'd like to be able to `watch 'tail filename'` output as it is produced, I find it useful for debugging
