### ISSUE TITLE
Documentation contains conflicting information about the version of htslib that has been wrapped

### ISSUE THREAD

**Issue by wholtz** [pysam-developers/pysam#1312]
The current start page of the documentation says that pysam v0.22.1 wraps htslib 1.21.  But the [release notes](https://pysam.readthedocs.io/en/v0.22.1/release.html) state pysam v0.22.1 wraps htslib 1.18.

**Comment by jmarshall** [comment]
https://pysam.readthedocs.io/ redirects to the stable documentation, which corresponds to the most recent release, currently 0.22.1. This is the version of the documentation that you probably want to be looking at, and is the default readthedocs version and is linked from PyPI.

The link in the sidebar of this repository — https://pysam.readthedocs.io/en/latest/ — corresponds to the in-development code in this git repository, which does indeed wrap HTSlib et al 1.21.

If there is an issue here, it is that the version number listed on the https://pysam.readthedocs.io/en/latest/ page is misleading. That will be fixed in due course with infrastructure changes.
