### ISSUE TITLE
Importing After Refactoring ('module' object has no attribute 'TestClass')

### ISSUE THREAD

**Issue by dnephi** [pysam-developers/pysam#146]
I don't know how many others have experienced this, but, with the latest round of refactoring, I'm unable to import pysam, though it will build and install. I've rolled back the version I use.

The recent changes have been excellent. for what it's worth. Great work.

Sample Traceback:

/mounts/anaconda/lib/python2.7/site-packages/pysam-0.8.4rc0-py2.7-linux-x86_64.egg/pysam/__init__.py in <module>()
      6 import pysam.cfaidx as cfaidx
      7 from pysam.cfaidx import *
----> 8 import pysam.ctabix as ctabix
      9 from pysam.ctabix import *
     10 import pysam.csamfile as csamfile

/mounts/anaconda/lib/python2.7/site-packages/pysam-0.8.4rc0-py2.7-linux-x86_64.egg/pysam/ctabixproxies.pxd in init pysam.ctabix (pysam/ctabix.c:13597)()
     39   ctypedef int uint64_t
     40 
---> 41 cdef class TupleProxy:
     42 
     43     cdef:

/mounts/anaconda/lib/python2.7/site-packages/pysam-0.8.4rc0-py2.7-linux-x86_64.egg/pysam/cutils.pxd in init pysam.ctabixproxies (pysam/ctabixproxies.c:13790)()
----> 1 #########################################################################
      2 # Utility functions used across pysam
      3 #########################################################################
      4 cimport cython
      5 from cpython cimport array as c_array

AttributeError: 'module' object has no attribute 'TestClass'

**Comment by AndreasHeger** [comment]
Thanks. I am trying to clean everything up so that will be easier for others to contribute. 

If you pulled the latest changes, could you please try removing all the 'c*.c' files? This forces the cythonization. It seems that setup.py can not detect if a .pxd file is more recent than the .c file. I am using the following to clean up my repository when I am developing to force a complete rebuild:
```
rm -rf build/ pysam/c*.c pysam/*.so pysam/*.pyc pysam/*~
```
Best wishes,
Andreas

**Comment by dnephi** [comment]
Thanks - looks like that worked.
