### ISSUE TITLE
C util force_bytes not converting from unicode before Python 3

### ISSUE THREAD

**Issue by sbandara** [pysam-developers/pysam#202]
Pybedtools 0.7.0 interval names and chromosomes are unicode strings in Python 2. A `TypeError` from pysam's `AlignmentFile.get_tid` can be traced to `force_bytes` in [cutils.pyx](pysam/cutils.pyx) not converting the contig string on Python 2.7.10. The relevant section is:
```python
cdef bytes force_bytes(object s, encoding="ascii"):
    u"""convert string or unicode object to bytes, assuming
    ascii encoding.
    """
    if PY_MAJOR_VERSION < 3:
        return s
    elif s is None:
        return None
    elif PyBytes_Check(s):
        return s
    elif PyUnicode_Check(s):
        return s.encode(encoding)
    else:
        raise TypeError(u"Argument must be string, bytes or unicode.")
```
Why do you convert from unicode only when `PY_MAJOR_VERSION` >= 3?

**Comment by AndreasHeger** [comment]
Thanks, this is because all strings in python3 are unicode and thus needed conversion. AFAIK, there is no unicode provision in the SAM/BAM spec.

Probably the best way is to convert unicode strings to python strings in 2.7 before submitting to pysam, that way you can ensure that they will be handled correctly.

Best wishes,
Andreas

**Comment by sbandara** [comment]
Yes, you are right. It's not in the spec. Many thanks for your attention.
