### ISSUE TITLE
Use of properties without caching in VariantRecord could cause unintentional performance problems

### ISSUE THREAD

**Issue by andyrimmer** [pysam-developers/pysam#210]
The lazy parsing implemented in VariantRecord is great, but currently caching of e.g. the INFO data must be done by the user of the class. If used in the following way, the user will incur the penalty of unpacking the INFO data many times without being aware of it unless they go and look into the code.

    for x in listOfPossibleInfoFields:
        if x in record.info:
            doSomethingWithX(x) 

One solution is to implement a per-instance cache on the VariantRecord class.

**Comment by AndreasHeger** [comment]
Thanks! It might take a little to implement this.

@bioinformed, what is your suggestion?

**Comment by bioinformed** [comment]
**Quick answer**
Is the following sufficiently faster?
```
    for key, value in record.info.iteritems():
        if key in setOfUsefulInfoFields:
            doSomethingWithInfo(record, key, value)
```

**Longer answer**
The current proxy classes and properties are pretty fast, in spite of the overhead involved in creating Python objects for keys and values every time they are accessed.  Do you have an example where the overhead is substantial relative to any real processing done in Python?  If so, the next simple optimization would be to cache Python string versions of chrom/info/format string keys.  Although easy enough to implement, I've put it off intentionally because it is possible for other non-pysam-aware C or Cython code to modify header objects under the hood.  This can lead to loss of coherence between the C and Python objects and could result in incorrect results or segmentation faults.

Full per-instance caches are certainly possible, but can also suffer from the same coherence problems and greatly increase the memory footprint of variant objects.  Unless cache management was extremely explicit, the extra storage overhead could easily make materializing modestly large sets of variants prohibitively expensive (say a few 10s of thousands).

**Comment by AndreasHeger** [comment]
Closing for now, let us see how this plays out in practice.
