### ISSUE TITLE
set_verbosity does not work for external htslib.

### ISSUE THREAD

**Issue by AndreasHeger** [pysam-developers/pysam#223]
See https://github.com/ga4gh/server/issues/335#issuecomment-180323480

**Comment by jeromekelleher** [comment]
I haven't tested this on an external htslib, only on internal htslib which is compiled in 'separate' mode. I think the issue is that we would need to have a ``cutils.set_verbose``, ``ctabix.set_verbose``, etc for each of the extension modules so that they could set ``hts_verbose`` for their own copy of htslib. There could then be a high-level function that calls all these functions internally to ensure that we set hts_verbose to the appropriate value everywhere.

I realise there are very good reasons for keeping all the modules separate and you've probably gone through all this before a dozen times, but have you considered compiling everything together as one 'super-module'? This way there would only be one copy of htslib, and these sort of quirks would go away. I don't have an real experience with Cython, so apologies if this is a stupid question!

**Comment by AndreasHeger** [comment]
thanks, I can see now what the problem is. The reason for the "separate" mode was that I could not find a way that worked for setup.py install/develop and that did not require setting an LD_LIBRARY_PATH. Putting everything into one mega-module was the previous state of affaris and the code become very unmanageable, Much has changed in cython and maybe there are better ways.
