### ISSUE TITLE
Bedcov regression in pysam 0.9

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#254]
I've found that `pysam.bedcov` seems to have stopped working on my installation.  

```
import pysam

bam = "my.bam"
bed = "my.bed"

lines = pysam.bedcov(bed, bam)
```

On pysam 0.8.4 I got a list of strings as output:

```
['chr1\t ...]
```

But on 0.9 I get

```
ERROR - failed to write data to stream: <closed file '<stdout>', mode 'w' at 0x100292150>
```

I'm using bioconda installs of pysam on python 2.7.  I've seen the same behavior on OSX and linux.

**Comment by kyleabeauchamp** [comment]
I have also tested using a non-bioconda build--still fails.  This still uses anaconda python 2.7, but I built pysam from source directly.

**Comment by kyleabeauchamp** [comment]
I'm also having problems with other samtools calls in pysam 0.9.  Here's a snippet (from https://github.com/etal/cnvkit/blob/master/cnvlib/coverage.py#L156):


```
def bam_total_reads(bam_fname):
    """Count the total number of mapped reads in a BAM file.
    Uses the BAM index to do this quickly.
    """
    lines = pysam.idxstats(bam_fname)
    tot_mapped_reads = 0
    for line in lines:
        _seqname, _seqlen, nmapped, _nunmapped = line.split()
        tot_mapped_reads += int(nmapped)
    return tot_mapped_reads
```

This function dies at the `line.split()` section with the following:

```
    _seqname, _seqlen, nmapped, _nunmapped = line.split()
ValueError: need more than 1 value to unpack
```

**Comment by kyleabeauchamp** [comment]
See also https://github.com/pysam-developers/pysam/pull/255/

**Comment by kyleabeauchamp** [comment]
Looks like this is a duplicate of #245

**Comment by fpepin** [comment]
I think it might not be an a duplicate of #245.

I'm hitting a very similar error when running pysam inside of ipython (v4.1.2) with Python 2.7.10 (on OS X). Checking online suggests that this might be an encoding error, but setting `PYTHONIOENCODING=UTF-8` as suggested does not work in my case.

Running the exact same code (`pysam.idxstats('my_bam.bam')`) works with interactive python instead of ipython.

The workaround for me is to just call the command-line samtools directly, but it feels a bit icky.
