### ISSUE TITLE
IndexError for reference sequence for reads with skipped regions

### ISSUE THREAD

**Issue by Emmett1938** [pysam-developers/pysam#296]
(Apologies if this issue is attributable to user error.)

When attempting to get the reference sequence from an aligned read containing an 'N' in the cigar string, Pysam encounters an IndexError. This happens using both .get_reference_sequence() and get_aligned_pairs(with_seq=True).

    Traceback (most recent call last):
        pairs = read.get_aligned_pairs(matches_only = True, with_seq = True)
      File "pysam/calignedsegment.pyx", line 1466, in pysam.calignedsegment.AlignedSegment.get_aligned_pairs (pysam/calignedsegment.c:16424)
      File "pysam/calignedsegment.pyx", line 1414, in pysam.calignedsegment.AlignedSegment.get_reference_sequence (pysam/calignedsegment.c:16094)
    IndexError: string index out of range

Using read.get_aligned_pairs(matches_only = True) works fine, so it seems to be an issue with retrieving the reference sequence. I am encountering this issue with pysam 0.9.0, but was not encountering it in 0.8.4. I suspect it may be related to issue #225.

**Comment by AndreasHeger** [comment]
Thanks, this might be due to how the MD tag is computed for a CIGAR string that contains an N.
Do you have an example?

So far I have treated N and D as equal, but I now see that you would not expect  bases skipped in the reference (N) to appear in the MD tag. As the N tag is supposed to represent introns you would not want to store large chunks of genomic sequence in the MD tag.
