### ISSUE TITLE
Editing fields in vcf headers gives error

### ISSUE THREAD

**Issue by AbhijitBadve** [pysam-developers/pysam#466]
I am trying to add additional filter in vcf header and getting rid of the original filter object generated by another tool. When I try to remove the header record it does it successfully. However I can't add the new header with the same ID. It gave me following error:
"Header already exists for id=PASS"
Code: 
f.header.filters.remove_header('PASS')
f.header.filters.add('PASS',None,None,'pindel tool filters passed')
f.header.filters.add('MITO_PASS',None,None, 'genedx filters size 1500 and frequency 1.5% pass')

As this didn't work, I tried to edit the description of the filter. But it produced another error:
"AttributeError: attribute 'description' of 'pysam.libcbcf.VariantMetadata' objects is not writable"
Code:
f.header.filters['PASS'].description='pindel tool filters passed'

**Comment by bioinformed** [comment]
Due to the complexity and fragility of wrapping the htslib C API, there are many limitations in the pysam VariantHeader API.  Some will be resolved in time, but there are just too many ways to crash the Python interpreter when altering metadata.  (Fine in C, where one has to be aware of low level details regarding memory management, but hard to translate into a generic object model in Python.)

Regarding your specific problems:
  * The "PASS" filter is reserved by the htslib implementation and one should not remove or alter it.  I can work on adding the ability to mutate the description, but it is a purely cosmetic thing.
  * The call to remove the header just removes the header line, but one cannot remove the header metadata or else subsequently reading records with that header will cause a segmentation fault.

**Comment by AbhijitBadve** [comment]
Gotcha. We did change in library to make this mutable. With additional testing, we will know if it breaks the interpreter.  Thanks for your explanation. Closing this now.
