### ISSUE TITLE
Upgrade to htslib 1.5

### ISSUE THREAD

**Issue by AndreasHeger** [pysam-developers/pysam#492]

**Comment by bioinformed** [comment]
I'm interested in this as well because of several important VCF bug fixes and the new logging API.  As usual, I also have another round of minor VCF bug fixes and some new features.

One other request -- can we convert the test suite to run with pytest?  I have a growing test suite for the BCF/BCF objects that uses pytest features that I currently maintain outside of pysam that would be useful to include.  The primary change is that the tests are run from the `pysam` directory, which requires that paths to data files be updated.

**Comment by AndreasHeger** [comment]
Great. I can do the import of the new code. Hopefully push the new branch this evening.

Yes, converting to pytest is not a problem. Will do that as well.

**Comment by AndreasHeger** [comment]
See #496

**Comment by bioinformed** [comment]
Any thoughts on connecting the new pysam logging system into the Python logging infrastructure?  I can work on this later in the week, if you think it is desirable.

**Comment by AndreasHeger** [comment]
I have focused so far on getting all the existing functionality to work, have not wrapped hts_log.h, sorry! Linking it in with the python logging infrastructure would be great. 
My biggest headache in this area are output samtools/bcftools tools to stdout/stderr, but I don't think these use the htslib logging infrastructure yet.

**Comment by AndreasHeger** [comment]
@bioinformed, tests now run using pytest.
