### ISSUE TITLE
pysam Samfile gives error reading bamfile

### ISSUE THREAD

**Issue by shashidhar22** [pysam-developers/pysam#51]
pysam Samfile give the following error when trying to read bamfile

Traceback (most recent call last):
  File "sam_flanker.py", line 10, in <module>
    bam_file = pysam.Samfile(input_file, "rb")
  File "csamfile.pyx", line 314, in pysam.csamfile.Samfile.__cinit__ (pysam/csamfile.c:4820)
  File "csamfile.pyx", line 491, in pysam.csamfile.Samfile._open (pysam/csamfile.c:6730)
ValueError: file header is empty (mode='rb') - is it SAM/BAM format?

**Comment by blaiseli** [comment]
I have the same problem with a bam file for which "samtools view -H" returns the following:
-----
@HD	VN:1.3	SO:coordinate
-----

Strictly speaking, the header is not empty. I just have no reads in it, which may happen when the sam file resulted from a mapping of an empty file, and is a arguably legitimate situation in an analysis pipeline.

**Comment by AndreasHeger** [comment]
Thanks, I will check this.

**Comment by lynxoid** [comment]
Any updates on the issue?

**Comment by lynxoid** [comment]
Some hints as to the cause of this here: https://code.google.com/archive/p/pysam/issues/104

Workaround: set `check_header=False` and `check_sq=False` when calling `fetch()`.

**Comment by AndreasHeger** [comment]
Not yet, will add a test case.

**Comment by AndreasHeger** [comment]
Thanks. I had a look and it seems to me that this is indeed a feature rather than a bug. 
Setting check_sq=False when opening the file is sufficient. Opened, it will return 0 for 
mapped and unmapped reads and fetch() will return an empty iterator.

I have added a test case covering this and modified the error message. On balance I would hesitate to disable the check at this stage - it is currently the primary way of detecting if the format is valid when opening a file.

Please reopen if you feel strongly about this.
