### ISSUE TITLE
BAM Header UnicodeDecodeError: 'ascii'

### ISSUE THREAD

**Issue by raqsilva** [pysam-developers/pysam#629]
I get this error due to a non-ascii character "µ" present in the BAM header under the "RG" tag/key and then "SM" tag/key. 

pysam==0.10 but also happens for 0.14, since the code responsible has not changed in libcutils.

Here is the output:

File "pysam/libcalignmentfile.pyx", line 1501, in pysam.libcalignmentfile.AlignmentFile.header.__get__ (pysam/libcalignmentfile.c:16750)
  File "pysam/libcalignmentfile.pyx", line 1468, in pysam.libcalignmentfile.AlignmentFile.text.__get__ (pysam/libcalignmentfile.c:16601)
  File "pysam/libcutils.pyx", line 84, in pysam.libcutils.from_string_and_size (pysam/libcutils.c:2551)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4805: ordinal not in range(128)

If I change the codec from "ascii" to "utf-8" it seems to be working fine for some methods, but haven't checked all.

Thanks!

**Comment by bioinformed** [comment]
The SAM file specification is intended to be ASCII only (based on discussions with the spec maintainers), with the intent that a future version will support UTF-8 encoding of certain attributes.  Until this is changed, pysam is behaving correctly, because your file is invalid.  

While utf-8 is fairly safe to use in SAM files, some unicode code points will break BAM encoding rules.  So encoding work-arounds at the pysam level are not sufficient and substantial changes to htslib will be needed to properly allow utf-8 support.  I know this isn't the most helpful answer, but the best fix is to stick to ASCII until the spec and htslib are updated.

**Comment by AndreasHeger** [comment]
Merging this with #688
