### ISSUE TITLE
Pysam.view report 'pysam.utils.SamtoolsError: "samtools returned with error 1: stdout=, stderr=samtools view: invalid option -- ' ''

### ISSUE THREAD

**Issue by ZIWEI-WONG** [pysam-developers/pysam#772]
Hi there, my pysam.view always report error1, even when I add 'catch_stdout=False'.
Would you mind to give me some advice?
My code is:
`pysam.view("-u -f 8 -F 260","/usr/local/virussite/input.bam > /usr/local/virussite/output2.bam", catch_stdout=False)`
or
`pysam.view("-u -f 8 -F 260","/usr/local/virussite/input.bam","-o","/usr/local/virussite/output2.bam", catch_stdout=False)`
Cheers!

**Comment by ijhoskins** [comment]
Hi @ZIWEI-WONG I don't know if this issue is related to the one I just created (https://github.com/pysam-developers/pysam/issues/813), but I have successfully used pysam.view with catch_stdout=False.

One thing I notice with your call is that you pass a single string with multiple flags. Maybe try passing each of your args as individual strings?

**Comment by jmarshall** [comment]
Indeed, the full message here is `invalid option -- ' '` and the issue is passing `…"-u -f 8 -F 260"…` rather than individual arguments `…"-u", "-f", "8", "-F", "260"…`.
