### ISSUE TITLE
pysam.cat finds invalid options that were not passed

### ISSUE THREAD

**Issue by ijhoskins** [pysam-developers/pysam#813]
Hello, 

I have found an issue with pysam.cat(), in which I get errors saying I have used invalid options. Yet, none of the options match what was used in the call args.

Example:
```
cat_args = ['-o', '/tmp/tmp33qgrabk.cat.bam', '/tmp/tmp9b1duxnw.masked.bam', '/tmp/tmpa30gy13u.primer.nonintersected.bam']
pysam.cat(*cat_args, catch_stdout=False)
```
returns
```
cat: invalid option -- '?'
cat: invalid option -- 'U'
cat: invalid option -- 'U'
cat: invalid option -- 'U'
Traceback (most recent call last):
...
 File "/home1/06285/ihoskins/bioinfo/analysis/seq_utils.py", line 464, in cat_bams
    pysam.cat(*cat_args, catch_stdout=False)
  File "/home1/06285/ihoskins/miniconda3/envs/CBS_variants/lib/python3.6/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=None, stderr=[main_cat] ERROR: input is not BAM or CRAM\n'
```

```
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:43:46) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.__version__
'0.15.2'
>>> pysam.__samtools_version__
'1.9'
```

I checked to verify the input files are BAM format. One of them happens to have no alignments, but I don't believe that is the issue. The problem appears to be parsing the call args, whereas the downstream error is probably caused by failure to identify the BAM files.

What is perplexing to me is that if I run the same call on the same files in an interactive python session (or if I just call from the command line with my own samtools distribution), the cat command runs just fine and produces the expected output. Furthermore, if I simply put a pdb breakpoint before the call in my script, then continue (c), the call completes without error. It also works if I simply step through the function. So, it seems the issue has to do with my environment, specifically when called from a script. I tried importing pysam just prior to the call, but that did not help.

Has anyone observed this behavior before? I recall experiencing the same type of error a few years ago with pysam.index() when specifically called from a script (and on a different architecture).

I am happy to provide my test files if that helps. Thanks in advance for any help!

**Comment by marcus1487** [comment]
I am also experiencing this same issue with `pysam.index()`. I am developing a larger package for nanopore sequence analysis ([Megalodon](https://github.com/nanoporetech/megalodon)) and on some systems I consistently get this error when running the `pysam.index()` step. I have had similar experience with the command working with no error immediately after the process has completed. I have even put `sleep(1)` calls right before the call to index, but still receive the same error. I had thought that this might have to do with open file handles to these bam files, but this does not seem to be the case. On some systems though (my local mac machine) I do not see this error though, so this does seem to be an environment specific issue.

**Comment by ijhoskins** [comment]
@marcus1487 it is helpful to hear others have encountered this issue. I have resorted to using subprocess calls but would like to avoid that if possible.

What systems did you encounter the problem on? Perhaps this is an issue with command line parsing utilities? Or multiple versions of samtools installed?

**Comment by marcus1487** [comment]
I've thought about using subprocess as well, but using pysam certainly feels like the "right" way to do this. I've mostly experienced this on ubuntu HPC clusters. I've also suspected that this might be an issue with multiple versions of samtools installed/in `PATH`.

**Comment by yotamcons** [comment]
We have experienced the same issue.
shortly - are program creates multiple BAM files, than uses pysam.merge(), and finnaly pysam.index()

We found that this happens when we run any pysam command after the merge command - be it pysam.quickcheck() or pysam.index(). To see that this is indeed a problem raising when running two commands in a row, I suggest trying to replace the second one.

like @marcus1487 I have not experienced this error on my local Mac, only on out remote unix cluster.

I have tried to use @ijhoskins recommendation from another thread (which matches [this paragraph from the documentation](https://github.com/pysam-developers/pysam/blob/6cf47e8688538514f0f6a440ba0944d51ecd7dbc/doc/usage.rst#using-samtools-commands-within-python)) to add the catch_stdout=False keyword to the first and second command,  and it did not solve the issue.

I have also tried to reload the package between the merge and the quickcheck and it did not solve the issue

**Comment by jmarshall** [comment]
The observation that this occurs when `index` or `quickcheck` (or a couple of other commands) is run **after other commands have been run** is key. It turns out that the problem is to do with incorrectly resetting `getopt()` parsing on Linux, hence problems only occur (1) on Linux, and (2) on the second or subsequent direct call to a samtools/bcftools subcommand in the same Python session. See #1085, which fixes the issue.
