### ISSUE TITLE
Module 'pysam' has no 'faidx' member

### ISSUE THREAD

**Issue by billzt** [pysam-developers/pysam#819]
I use ` pysam.faidx(XXXXXXXXXXXXXXX)` and the scripts run properly. However `pylint` always complains that:
```
 Module 'pysam' has no 'faidx' member
```

Such errors annoyed me!

**Comment by jmarshall** [comment]
This happens because these members are dynamically added to the `pysam` module (see _pysam/samtools.py_ etc). The list of samtools subcommands doesn't change very often, so it would be possible to recode this so they weren't dynamically added and avoid these errors.

In the meantime, you can avoid these messages by adding to your _.pylintrc_:

```
[TYPECHECK]
generated-members=pysam.faidx,pysam.view,pysam.etc
```
