### ISSUE TITLE
Error with pip install 0.15.2 on OS X

### ISSUE THREAD

**Issue by Amar1729** [pysam-developers/pysam#828]
I use `homebrew` with `pip` (not `conda`).
Attempting to install `pysam==0.15.2` on darwin 10.14.5.

Issue
====
`pip install pysam`

Will result in a build failure due to missing `lzma` headers:
```
    htslib/cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found
    #include <lzma.h>
             ^~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
```

Solution
======

```
export LDFLAGS=-L/usr/local/opt/xz/lib
export CPPFLAGS="-I/usr/local/opt/xz/include"
```

(or exporting those to wherever your libraries live, that's the default homebrew path) and then running `pip install pysam`.

Not sure where's the best place for this info in your documentation.

**Comment by jmarshall** [comment]
Homebrew also puts that header in _/usr/local/include_, where you would think the compiler would be looking, but when compiling pysam's C code it does not (at least in some circumstances, on macOS).

Better solution is to fix the pysam build script bug that leads to inconsistency whereby different parts of the build do or do not look for headers in that directory — fixed by PR #829.
