### ISSUE TITLE
What's the difference between query_length and reads length?

### ISSUE THREAD

**Issue by renzilin** [pysam-developers/pysam#911]
Hi developers, I think that I have one issue that when I'm working on long-reads dataset.
I used pysam to extract some information in bam file. One of them is `query_length`. But I found that there are 3 results from one read:
![image](https://user-images.githubusercontent.com/17135904/80047779-590e4380-84dc-11ea-8aae-3b7825db9acd.png)
We can see that the **read_length** is the result from `line.query_length`. The length of read that I want is what in fastq. Therefore, the read length should be the same if they are from the same read. But they are not in this result.

Could you please provide me some information about that? Much appreciated! Thank you!

**Comment by kevinjacobs-progenity** [comment]
I suspect your aligner is hard-clipping supplementary alignments, which removes bases not considered in the alignment from the query.  The primary alignment (flags=16) is the longest, while the two supplementary alignments (flags=2048, 2064) are shorter and presumably hard clipped.  This is the default behavior of many aligners, since supplementary alignments are often quite a bit shorter than the primary.  If so, then to recover the actual read lengths only consider primary alignments.

**Comment by renzilin** [comment]
> If so, he actual read lengths can be recovered by only considering primary alignments.

Thanks for your quick reply. It seems that I need to filter non-primary reads when I summary the distribution of read length.

**Comment by renzilin** [comment]
> I suspect your aligner is hard-clipping supplementary alignments, which removes bases not considered in the alignment from the query. The primary alignment (flags=16) is the longest, while the two supplementary alignments (flags=2048, 2064) are shorter and presumably hard clipped. This is the default behavior of many aligners, since supplementary alignments are often quite a bit shorter than the primary. If so, he actual read lengths can be recovered by only considering primary alignments.

Thanks for your quick reply. It seems that I need to filter non-primary reads when I summary the distribution of read length.
