### ISSUE TITLE
Substitutions not always in lowercase

### ISSUE THREAD

**Issue by ExpectationMax** [pysam-developers/pysam#926]
Dear pysam developers,

I am using pysam to extract per nucleotide substitution statistics from an alignment. In doing so I noticed some strange behavior of pysam which is not in line with the documentation.

Namely, the result of `AlignedSegment.get_aligned_pairs(with_seq=True)` does not always return substitution errors in lowercase as indicated in the documentation. While mostly this is the case, some of the substitutions are actually returned in uppercase. This seems to be happen when there was a deletion directly before the substitution.

You can find a file to recreate the issues containing two of the reads that I found to show this behavior here: [recreate_issue.sam.gz](https://github.com/pysam-developers/pysam/files/4740002/recreate_issue.sam.gz). Using the code below it is evident that some of the substitutions are encoded in upper and some in lowercase. The pysam version I used is `0.15.4`

```python
import numpy as np
import pysam

def compute_substitutions(read):
    alignment_info = np.array(read.get_aligned_pairs(matches_only=True, with_seq=True))
    query_positions = alignment_info[:, 0].astype(int)
    matched_reference_sequence = alignment_info[:, 2].astype('U1')
    matched_query_sequence = np.fromiter(read.query_sequence, 'U1')[query_positions]
    mismatch_positions = np.where(matched_query_sequence != matched_reference_sequence)[0]
    substitutions = ['{}->{}'.format(matched_reference_sequence[pos], matched_query_sequence[pos]) for pos in mismatch_positions]
    cigar_stats = read.get_cigar_stats()[0]
    assert len(mismatch_positions) == (cigar_stats[10] - cigar_stats[1] - cigar_stats[2])
    return substitutions

print(pysam.__version__)
with pysam.AlignmentFile('recreate_issue.sam', 'r') as f:
    for read in f:
        print(compute_substitutions(read))
```

The output is:
```python
0.15.4
['g->T', 'a->G', 'A->G']
['a->C', 'T->C', 'A->T']
```

My hypothesis is that something is going wrong in [build_alignment_sequence](https://github.com/pysam-developers/pysam/blob/2282e99dde733360491cedfbfa6a8b6a4d191d6d/pysam/libcalignedsegment.pyx#L699), but I was not able to pinpoint it down in more detail.

Cheers,
Max

**Comment by jmarshall** [comment]
This is the same problem as #895. Examining the CIGAR and MD fields of your _recreate_issue_ reads we can see inconsistencies in the MD strings as to how the strings of deleted bases are set off from any immediately following substitution:

```
7=1X27=1X57=8D1X15=                 7=1X27=1X57=8D        1X15=
7G27A57^TCTGTCTGA15                 7 G 27 A 57 ^TCTGTCTG A 15

3=1D9=2D16=2D1X31=2D2X21=3D6=1D17=  3=1D 9=2D  16=2D    1X31=2D  2X21=3D   6=1D 17=
3^G9^AC16^TC0A31^GCTA21^GTC6^T17    3 ^G 9 ^AC 16 ^TC 0 A 31 ^GC TA21 ^GTC 6 ^T 17
```

I expect you are seeing two or three unexpected capitals here: in the first read, the `A` after the deletion; in the second read, the `TA` after the `GC` deletion. In all the other cases, there is a numerical item between the deleted bases and the following substitution — including in the second read where there is a `0` between `^TC` and `A` which would otherwise be adjacent.

The [MD string](http://samtools.github.io/hts-specs/SAMtags.pdf) (as recently clarified in samtools/hts-specs#500) requires a `0` between otherwise adjacent deleted and substitution bases. So while it would be possible to improve `build_alignment_sequence()` to deal with this (as an extension beyond the spec), these MD strings are not in accordance with the specification as it stands and they would be parsed incorrectly by other tools.

What program was used to produce these MD strings in these SAM records?

**Comment by ExpectationMax** [comment]
Hey John,

thanks for the fast response.
I though that what you explained might be the case but I was not entirely sure how to interpret the MD string specification. The alignment file was generated using BBMap, thus this seems to be an issue on their side. I will try to contact the developer and close this for now as the behavior is in line with the specification.

Cheers,
Max

**Comment by jmarshall** [comment]
> I was not entirely sure how to interpret the MD string specification.

Were you trying to interpret the specification before or after the recent improvements? Do you find that the current text on p3 of [SAMtags.pdf](http://samtools.github.io/hts-specs/SAMtags.pdf) explains MD clearly? If not, which parts need further improvements?

**Comment by ExpectationMax** [comment]
> Were you trying to interpret the specification before or after the recent improvements?
It seems like I was looking at a not up to date version of the specification.

> Do you find that the current text on p3 of SAMtags.pdf explains MD clearly? If not, which parts need further improvements?

In the current version you linked to the text is very clear. I solely think that a simple example would help to underline the point. This could also work by extending the sample in place to incorporate this edge case.
