### ISSUE TITLE
Failed reading ASCII encoded vcf files with special characters

### ISSUE THREAD

**Issue by olingerc** [pysam-developers/pysam#998]
First, thanks for the great library!

I have a ASCII encoded VCF file with non-standard characters in the INFO field. A minimal example would be:
```
##fileformat=VCFv4.2
##contig=<ID=1,length=249250621>
##INFO=<ID=ILoveFrance,Number=R,Type=String,Description="Everybody should">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample
1	65529	.	C	T	16.65	.	ILoveFrance=Télomère	GT	0/1
```
In windows simply use notepad and make sure that when saving you use "ANSI" encoding.

The following code will fail with `UnicodeDecodeError` with pysam version 0.16.0.1
```python
from pysam import VariantFile

vcf_in = VariantFile(filename="test.vcf", mode="r")

for v in vcf_in.fetch():
    print(v.info.items())
```

This line in the pysam code raises the exception in [libcbcf.py](https://github.com/pysam-developers/pysam/blob/746e4d9bd149722f2dbdb99b1e15760a7c2b7979/pysam/libcbcf.pyx#L287):

```python
value = tuple(v.decode('utf-8') if v and v != bcf_str_missing else None for v in b.split(b','))
```

Does that mean that pysam will always force to UTF-8? I can of course convert the file to UTF-8 beforehand, but my tool needs to be able to work with every possible incoming VCF file. Is there any way to handle the exception and try to decode the string myself?

Full exception:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(v.info.items())
  File "pysam/libcbcf.pyx", line 2750, in pysam.libcbcf.VariantRecordInfo.items
  File "pysam/libcbcf.pyx", line 2741, in iteritems
  File "pysam/libcbcf.pyx", line 555, in pysam.libcbcf.bcf_info_get_value
  File "pysam/libcbcf.pyx", line 287, in genexpr
  File "pysam/libcbcf.pyx", line 287, in genexpr
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte
```

**Comment by bioinformed** [comment]
Quick answer:

   - Your input file isn't valid VCF, so you'll need to encode it as UTF-8
   before parsing it with pysam.

Long answer:

   - Older versions of VCF support only ASCII files, which requires that
   all characters are in the ASCII range
      - i.e. your input file isn't ASCII.  It is mostly ASCII except some
      non-ASCII characters in INFO fields
      - Many VCF parsers do not enforce character encoding rules or attempt
      to decode strings into a known encoding (e.g. unicode), so many
invalid VCF
      files are created and mostly "just work"
   - Newer version of VCF were expanded to allow UTF-8 encoded files (a
   superset of ASCII)
      - The specification only allows for UTF-8 as a character encoding
      - There is no mechanism to specify an alternative encoding for the
      entire file or specific fields, so VCF parsers have no way to
know that an
      alternative encoding was used or how to decode such strings
   - This means that spec conforming VCF files cannot contain non-UTF-8
   characters
      - Sadly, we all know that many VCF files in the wild are
      non-conforming and practical software has to work around this as
best they
      can
   - pysam does enforce this restriction, although other VCF parsers may
   not.
      - pysam provides an API that transforms VCF values into Python types
      based on the field metadata.
         - Other parsers are simpler and treat values as strings and
         require the user to perform type conversions.
      - pysam has two options when it finds a non-UTF8 string:
         - (1) raise an error or
         - (2) pass it back to the user as an encoded byte string.
      - pysam takes the former approach (raising an error), since the API
      would be (even more) complex if it allowed string values to be
represented
      by a mixture of UTF-8 strings and undecoded byte strings (most users
      wouldn't appreciate it and most application authors wouldn't properly
      handle it)

So your best solution is to fix the upstream tool to generate valid VCF.
If that isn't possible, then you'll need to convert your input VCF into
UTF-8 with knowledge of what encoding was used.

Hope this helps...

**Comment by olingerc** [comment]
Dear @bioinformed,

Many thanks for taking the time to give such a detailed and complete answer. I have the feeling I am not the first person to address this although I did not find any issues here on Github. The first things 

I tell my new students is: 50% of the tasks of a bioinformatician is converting data from A to B because there are no mandatory standards and every software tool mainly tries to work within their own walls and do not think about inter-tool usage. Many lengthy specification documents exist but people generally work around these. Unfortunately this will not change.

Although I would have preferred you had chosen option 2 to handle this issue I completely understand why you did not.

Concerning my usecase, I will have to train the users then to watch out what they give me. This particular VCF was created by the CLC Workbench, so even big tools are not safe from this.

Best regards and thanks again for the great library.

**Comment by jmarshall** [comment]
While VCF v4.3 is clear that the file is to be encoded as UTF-8, the earlier v4.1 and v4.2 specifications don't mention the issue explicitly. At best, you could extrapolate from the mentions of “ASCII” in the BCF parts of the specifications that those versions of VCF might be limited to ASCII, but really it's unclear. So it's really only “common sense assumptions (by English speakers) around the default” that make the earlier versions ASCII-only. Hence it's not surprising that from time to time people have put e.g. Latin-1-encoded characters in such fields — though they'd be about as justified in putting UTF-8-encoded characters there and this would in fact be easier for implementations that are handling UTF-8 for v4.3 anyway.

And the example given is a VCF v4.2 file.

Pysam is a library used by other scripts. As a library, it would ideally allow practical software that uses pysam to work around encoding problems as best they can, by allowing such scripts to control what they want to have happen for these unfortunately encoded fields — rather than just refusing and raising an exception.

> - pysam has two options when it finds a non-UTF8 string:
>         - (1) raise an error or
>         - (2) pass it back to the user as an encoded byte string.

Anyway, all this philosophy is irrelevant as fortunately there exists an option (3): take advantage of Python's impressively flexible facilities to enable user scripts to tell pysam what to do when it finds a non-UTF-8 string. It turns out that the [decode() function](https://docs.python.org/3/library/stdtypes.html#bytes.decode) allows callers to specify an [error handler](https://docs.python.org/3/library/codecs.html#error-handlers) that can even be user-defined. All pysam has to do is allow user scripts to control it, which is easiest with a global variable and getter/setter methods, similarly to the existing `get_verbosity()`/`set_verbosity()`.

Hence PR #1001, which allows @olingerc to add one line of code to have Latin-1-encoded `ILoveFrance=Télomère` fields be accepted:

```python
pysam.set_codec_error_handler('pysam.latin1replace')
```

Other built-in standard error handlers such as `'replace'` and `'backslashreplace'` may also be of interest.

**Comment by kevinjacobs-progenity** [comment]
@jmarshall : Thanks!  Using an error handler is a great idea and I didn't think of it before.  I'll review the PR shortly.

**Comment by olingerc** [comment]
@jmarshall Thanks for providing this incredible useful PR and thanks @kevinjacobs-progenity for reviweing it. You made my day and more... I could have proposed a PR myself and I will make sure to do exactly that the next time I encounter an issue.
